# Generated by Django 5.1.6 on 2026-07-05 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('low_attendance_notice', 'Low Attendance Notice'), ('weekly_summary_report', 'Weekly Summary Report')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], default='drafted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
