# Generated by Django 5.1.6 on 2026-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_id']},
        ),
    ]
