# Generated by Django 5.1.6 on 2026-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_options_class_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
    ]
